listen_addr: "0.0.0.0:8080"
global_timeout_ms: 5000
max_connections: 10000
routes:
  "/api":
    upstream: "http://api:3030"
    strip_path_prefix: true
    preserve_host_header: true
    timeout_ms: 3000
    retry_count: 2
   
  "/":
    upstream: "http://frontend:4173"
    strip_path_prefix: false    # Added this required field
    preserve_host_header: true
    timeout_ms: 1000
    retry_count: 1