listen_addr: "0.0.0.0:8081"
global_timeout_ms: 5000
max_connections: 10000

routes:
  "/api/critical":
    upstream: "http://critical-backend:8080"
    priority: 100
    timeout_ms: 1000
    retry_count: 3
  "/api":
    upstream: "http://localhost:8080/docs"
    priority: 50
    timeout_ms: 3000
    retry_count: 2
  "/":
    upstream: "http://localhost:8080/"
    priority: 0
    timeout_ms: 5000
    retry_count: 1