apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbr-router-dev

bases:
  - ../../base

commonLabels:
  environment: development

patches:
  - target:
      kind: Deployment
      name: harbr-router
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi

configMapGenerator:
  - name: harbr-router-config
    behavior: merge
    literals:
      - RUST_LOG=debug