apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: harbr-router-prod

bases:
  - ../../base

commonLabels:
  environment: production

patches:
  - target:
      kind: Deployment
      name: harbr-router
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 2Gi

configMapGenerator:
  - name: harbr-router-config
    behavior: merge
    literals:
      - RUST_LOG=info